### ISSUE TITLE
Video keeps buffering

### ISSUE THREAD

**Issue by FreeBornAngel** [yewtudotbe/invidious-custom#102]
I don't know if this is a yewtube issue or what, but it started more than a few days ago that the videos are unwatchable due to buffering.
In the first few days I could switch instances and the videos played just fine.
But, now a week or ten days after it started it has extended to all instances I have checked.

Is utub doing this, or what?
Can it be fixed?

I'm using brave on a linux box, if that matters.

**Comment by unixfox** [comment]
using dash or not?

**Comment by FreeBornAngel** [comment]
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/2ac9728d-e074-4984-b8f4-fc33b24b3e87)

Yes.

**Comment by unixfox** [comment]
Hum no you aren't using DASH.

For using dash you need "Preferred video quality:" set to DASH

**Comment by FreeBornAngel** [comment]
Ah, the line above.
Should I turn that on?

**Comment by unixfox** [comment]
please give the URLs where it's buffering. I can't replicate the issue on either DASH or non DASH.

**Comment by FreeBornAngel** [comment]
https://yewtu.be/watch?v=TCkp493lGYI
https://yewtu.be/watch?v=soHJjw2MS2M

Both of these are buffing for me.

**Comment by FreeBornAngel** [comment]
Ok, thank you.

**Comment by FreeBornAngel** [comment]
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/4375298e-f487-4035-94f9-d818567086ee)

I'm still getting buffered.

**Comment by unixfox** [comment]
Not possible, it loads the video pretty quickly for me. Make sure to enable javascript though as DASH needs javascript.

**Comment by FreeBornAngel** [comment]
Ok, thank you.

**Comment by unixfox** [comment]
probably fixed since then
