### ISSUE TITLE
hd720 proxy not working - itag not found - QI96hnhcr2E

### ISSUE THREAD

**Issue by Tsuchimikado** [yewtudotbe/invidious-custom#103]
https://yewtu.be/watch?quality=dash&v=QI96hnhcr2E
error messages are
`DASH request error at URL: /api/manifest/dash/id/QI96hnhcr2E?local=true&unique_res=1&hmac_key=d9c6da1d9614eb7e1ba69374e824a8f200da6aa1` (rare)
and
`The media could not be loaded, either because the server or network failed or because the format is not supported.` (most of times)

hd720 is ok in Microsoft Edge 124.0.2478.97 and Firefox 125.0.3

other invidious instances are ok with both dash and hd720

UPD: hd720 in proxy mode is not working
https://yewtu.be/watch?quality=hd720&local=true&v=QI96hnhcr2E
`The media could not be loaded, either because the server or network failed or because the format is not supported.`

**Comment by unixfox** [comment]
dash works for me. about hd720 in proxy mode failing, I'll take a look at.

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/475
