### ISSUE TITLE
Video won't load. Watch on the latest version of YouTube.

### ISSUE THREAD

**Issue by sunlightspectre** [yewtudotbe/invidious-custom#104]
Mentioning here, because my note got buried in [4725.](https://github.com/iv-org/invidious/issues/4725)  
This issue is either not only affecting improperly configured instances, or yewtu.be's rotator is not set up properly.  
Not sure which, but seems to affect about 50% of video views.  
[Console.](https://i.postimg.cc/nhr8TPS4/a9fia39fia9fi9a.png)

**Comment by unixfox** [comment]
For some unknown reasons the ipv6 rotation is not firing up. I'll investigate. Meanwhile it works when the ipv6 rotation has worked.

**Comment by sunlightspectre** [comment]
Thanks for the quick check.  
I have no clue _why_ it seems to not fire up, and will comment at you if I can figure out why.  
Otherwise, much obliged for confirming I'm not losing the last of my marbles, haha. Take care out there.
