### ISSUE TITLE
Instance unusable

### ISSUE THREAD

**Issue by 3hr80FEZwlir** [yewtudotbe/invidious-custom#105]
After waiting for a week or so, finally decided to ask - what's going on? 

During this time I've only been able to play one material. For tenths of others, instead of the video I've seen errors like "Use latest version of YouTube", "You've encountered an error"  and today, for the first time, "This helps protect our community. Learn more".

Is it the YouTube fighting with Invidious?

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4734
