### ISSUE TITLE
Direct Links not working

### ISSUE THREAD

**Issue by dt192** [yewtudotbe/invidious-custom#107]
The links given when you use the share feature don't embed and also just take you to the front search page rather than to the video.

https://yewtu.be/4QA2PFyMTCY (This doesn't work or embed)
https://yewtu.be/watch?v=4QA2PFyMTCY (This does both ok)

![2024-08-29_11-27_1](https://github.com/user-attachments/assets/fe8aa624-be51-4903-9838-af13c12d1df3)

**Comment by unixfox** [comment]
Upstream issue.
