### ISSUE TITLE
Consider adding a weak TLS cipher to give old devices another chance

### ISSUE THREAD

**Issue by zJudGenie** [yewtudotbe/invidious-custom#112]
Hi, I have an old iPad 2 and my mom used it to watch recipes on YT, some time ago I suggested her to use an Invidious instance as it is so much lighter than YT full of ads. Sadly we cant use yewtu.be instance because iOS 8.4.1 does not support latest TLS ciphers.

I know that for security reasons you restricted the list to the minimum, as I have seen here https://www.ssllabs.com/ssltest/analyze.html?d=yewtu.be&s=104.244.72.25 
the handshake fails with iOS 8.4.1 because we need at least `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384`.
You can find here https://www.ssllabs.com/ssltest/viewClient.html?name=Safari&version=8&platform=iOS%208.4&key=85 the list of ciphers supported by iOS 8.4.1.

I know that weak cipher should be avoided, but are they a real threat in this case?

**Comment by unixfox** [comment]
Feel free to install invidious on your computer or server: https://docs.invidious.io/installation/

I'm not weakening the security of my instance sorry.
