### ISSUE TITLE
403 error when attempting to access RSS feeds.

### ISSUE THREAD

**Issue by not-a-ethan** [yewtudotbe/invidious-custom#113]
When I try and access an RSS feed for a channel (weather its in my RSS reader (fluent reader) or in my browser I get a 403.

![image](https://github.com/user-attachments/assets/788cd692-f0e2-48ec-ad73-0bd9529a70c7)

**Comment by unixfox** [comment]
hello, yes I had to block RSS feeds otherwise youtube would block the whole instance. it's related to https://github.com/iv-org/invidious/issues/5032

sorry you will have to use another instance or install youtube locally on your computer.
