### ISSUE TITLE
[xcancel.com] Fails to load on usernames that begin with the word "static"

### ISSUE THREAD

**Issue by NintendoManiac64** [yewtudotbe/invidious-custom#114]
Yes, I know that this git is for yewtu.be and not xcancel.com but I can't find any place to report bugs for specifically xcancel.com rather than nitter in general as this bug does not happen on nitter.poast.org for example. Therefore the best I could do is to report this bug on an issue tracker for a different one of your projects (or rather, the only project you even have an issue tracker for).

Simply put, any username that begins with the word `static` fails to load. For example:

- https://xcancel.com/statice
- https://xcancel.com/staticy
- https://xcancel.com/static1

Compare to:

- https://nitter.poast.org/statice
- https://nitter.poast.org/staticy
- https://nitter.poast.org/static1

(these accounts are actually just random ones I found to more easily test this issue specifically in that they're all just the word `static` followed by only a single additional character)

**Comment by unixfox** [comment]
Moved to https://github.com/unixfox/nitter-fork/issues/8
