### ISSUE TITLE
Low audio bitrate when using DASH.

### ISSUE THREAD

**Issue by Vaeryus** [yewtudotbe/invidious-custom#64]
When you select DASH to watch videos, the audio quality gets really bad no matter what video quality you choose. Yewtu is the only instance that I have tried with that problem.
I am running OpenSUSE Tumbleweed, and I am using Librewolf (Flatpak). Disabling U-Block Origin does not fix the issue. I don't have the issue on my Android Phone for the most part. But I have also noticed that the sound suffers on certain videos as well.
I have also noticed that some instances offer a seprate option to change the audio quality whilst watching a video. What is up with that?

How to reproduce:
-open Yewtu on Librewolf (Flatpak)
-enable DASH in the options
-watch a video

**Comment by unixfox** [comment]
probably fixed since then
