### ISSUE TITLE
Issue with the Morph Browser on Ubuntu Touch

### ISSUE THREAD

**Issue by Vaeryus** [yewtudotbe/invidious-custom#65]
When you open a video on the Ubuntu Touch Browser Morph, you get the error message “The media could not be loaded, either because the server or network failed or because the format is not supported.” First I just assumed that the Morph Browser lacks some features, but other instances and Youtube itself work just fine.

How to reproduce:
-open Yewtu on the Morph Browser
-try to watch a video

**Comment by unixfox** [comment]
It doesn't work by default so without touching any settings?

Did you try with DASH or proxy enabled?

**Comment by Vaeryus** [comment]
I have just double-checked, and it doesn't work, even if I use DASH, proxy enabled or both combined.
