### ISSUE TITLE
Videos are broken

### ISSUE THREAD

**Issue by FreeBornAngel** [yewtudotbe/invidious-custom#69]
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/84b7ecca-a953-4c01-b268-dbf6319ee67f)

I've been getting this all day.
It's not just this video, but any video I've tried to watch.
I'm using brave on a linux box.

**Comment by FreeBornAngel** [comment]
>I'm working on it.

Wonderful.
Thank you.,

What is dash?

**Comment by unixfox** [comment]
It's for getting 1080p+ quality.

Check https://yewtu.be/preferences

**Comment by FreeBornAngel** [comment]
Videos are back!
Thanks for fixing that.

**Comment by FreeBornAngel** [comment]
Spoke too soon.

**Comment by unixfox** [comment]
I have not yet had the time to work on it.

Meanwhile like I said if you do what I said above you won't run into issues anymore

**Comment by FreeBornAngel** [comment]
I don't understand what I need to do.
I tried changing settings for dash from auto to 2 different settings, but didn't notice any changes.
What I did notice was that youtube put a cookie on my browser when I used it directly that wouldn't let the privacy redirect extension redirect, I had to delete the cookie.

**Comment by Fish25op** [comment]
https://github.com/FreeTubeApp/FreeTube/pull/3719

**Comment by unixfox** [comment]
recently fixed
