### ISSUE TITLE
LOGIN: Registration has been disabled by administrator. 

### ISSUE THREAD

**Issue by jtorrex** [yewtudotbe/invidious-custom#74]
Hi,

I've been using the instance usually logged with a user to follow some channels as Favorites.

Trying to log in today to the instance I saw this message:

 "Registration has been disabled by the administrator."
 
 Is there something that is being modified/corrected, or this change is intended to be permanent?

Thanks for your feedback!

**Comment by unixfox** [comment]
https://gist.github.com/yewtudotbe/c16a69ddad88a37c2a364a5ff5359197

**Comment by jtorrex** [comment]
Thanks for your clarification @unixfox! It's sad as I was using happily yewtube for a lot of time. Maybe an alternative is to allow users to be registered but advertise to them that the Subscriptions and personal configuration may be lost at some time, giving them the responsibility of keeping their personal configuration properly exported and backed up (as I did).
