### ISSUE TITLE
"This media could not be loaded" error for some videos

### ISSUE THREAD

**Issue by boytwink** [yewtudotbe/invidious-custom#76]
Example URL: https://yewtu.be/watch?v=glZK5114OlY

![Screenshot_20230809_210846_Firefox Nightly](https://github.com/yewtudotbe/invidious-custom/assets/135167145/0b51586e-6033-430a-837a-5e0ad85381f3)

Unaffected URL: https://yewtu.be/watch?v=jNQXAC9IVRw

![Screenshot_20230809_211148_Firefox Nightly](https://github.com/yewtudotbe/invidious-custom/assets/135167145/d235c663-4ec5-4543-8d11-7a79283d6286)

Originally reported on [reddit](https://old.reddit.com/r/degoogle/comments/15mdfnr/) and reproduced by me. Confirmed to work fine on at least the invidious.projectsegfau.lt instance

Edit: looks like https://github.com/iv-org/invidious/pull/4037 solves this, just needs to be integrated into this version

**Comment by unixfox** [comment]
Haven't had the time yet to update invidious. Will do it hopefully in the coming days.

**Comment by unixfox** [comment]
Should be fixed, I've updated invidious.
