### ISSUE TITLE
The media could not be loaded...

### ISSUE THREAD

**Issue by airone506** [yewtudotbe/invidious-custom#78]
First, I would like to thank you for hosting the service. You are awesome!

For around a week I am getting `The media could not be loaded, either because the server or network failed or because the format is not supported.` error for any video on yewtu.be. The error started to appear like 2-3 weeks ago for some videos only. Now the error occurs for every video (including the bookmarked ones in the past, before error started to appear). The other instances of invidious work fine. Is it just me or everyone is getting the same error?

**Comment by unixfox** [comment]
https://github.com/yewtudotbe/invidious-custom/issues/76
