### ISSUE TITLE
Videos autoplaying on external sites w/libredirect

### ISSUE THREAD

**Issue by mike-cuche** [yewtudotbe/invidious-custom#81]
Hello, i'm using Librewolf with the LibRedirect extensions to replace all youtube embedded videos in third party sites with yewtube ones.

However, it happens randomly, that all embedded videos inside a webpage start all togheter making the experience really annoying.

I do have cookie cleaning set at browser exit, and this issue does not seem to happen with other instances.

**Comment by unixfox** [comment]
Autoplay is just enabled by default that's it. LibRedirect should support some way to disable the autoplay if you don't want to have all the video autoplaying. At least Privacy Redirect support it.

I can't do anything more on my side sorry!
