### ISSUE TITLE
This content isn't available video

### ISSUE THREAD

**Issue by BangDroid** [yewtudotbe/invidious-custom#82]
What does "This content isn't available." mean? It's an actual video file that is loaded but is just this text. If I switch instances the video plays. This is more of a question than a bug or issue, but I couldn't really find anything specific in the docs.

**Comment by unixfox** [comment]
it means you have not paid your rent to youtube.

**Comment by BangDroid** [comment]
How does one go about paying rent to YouTube? Obviously this isn't literal, I just don't know what it means or what is implied.

Also, still happening, just a couple videos at random: https://yewtu.be/watch?v=zAxmn4ihqNg & https://yewtu.be/watch?v=KrLj6nc516A

**Comment by unixfox** [comment]
> How does one go about paying rent to YouTube? Obviously this isn't literal, I just don't know what it means or what is implied.
> 

It's a joke 😆😆

**Comment by unixfox** [comment]
Closing as it's youtube trying to block the instance but failing to do it. I did re-enforce the bypass scripts.
