### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by b9chomps** [yewtudotbe/invidious-custom#83]
Videos are not available in DASH quality. Issue persists since Sept 28th. Occurs on all videos I try to open.
HD720 is working.
Tried to delete cookies, restart , ... 
Occurs with Librewolf, Firefox and Ungoogled Chromium. OS: Linux.

**Comment by unixfox** [comment]
Unfortunately don't have the time for fixing that until 9th October.

**Comment by FreeBornAngel** [comment]
> Unfortunately don't have the time for fixing that until 9th October.

No hurries, for me.
I just wanted  to make sure someone was aware of it.

**Comment by unixfox** [comment]
Just came back from vacations and fixed the issue.

**Comment by FreeBornAngel** [comment]
Thank you!
You're the best.

**Comment by Veeno** [comment]
It started happening again today.

**Comment by FreeBornAngel** [comment]
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/960c3913-ac70-4aa7-b5f0-db67f7c3683d)

I think they get notified right away for this kind of error.
I saw this a few days ago and it fixed itself, presumably with help.

**Comment by FreeBornAngel** [comment]
> It started happening again today.

If you will copy the url stating with watch and switch instances pasting the partial link after the instance's url, it should work on one of the different instances.

watch?v=K7f6uevARno

This is the part of the link you will need.

**Comment by unixfox** [comment]
This is a common issue across all the invidious instances: https://github.com/iv-org/invidious/issues/4045

I don't have an automated system for changing the IP address of my server, so it's a manual process. I just changed the IP address so it's fixed.

**Comment by FreeBornAngel** [comment]
Thank you!
