### ISSUE TITLE
Videos not playing.

### ISSUE THREAD

**Issue by FreeBornAngel** [yewtudotbe/invidious-custom#84]
I use brave and when I open the videos in the brave tor browser they often work just fine, but if I just open them they don't play.
This has been ongoing for number of days.
Intermittently, the videos play a few seconds and buffer, play a few seconds and buffer, but that is video specific, I can come back weeks later and that video still won't play smoothly.

I hope these can be fixed.

**Comment by unixfox** [comment]
https://github.com/yewtudotbe/invidious-custom/issues/83
