### ISSUE TITLE
Comments not available when referrer isn't set (429)

### ISSUE THREAD

**Issue by mutexd-service** [yewtudotbe/invidious-custom#85]
Hello, thank you for hosting this instance.
When disabling the referrer header on firefox the comment API returns '429 Too Many Requests'
Thanks.

**Comment by unixfox** [comment]
Unfortunately this is to combat against bot abuse.

If you do not want to send the full referrer then at least send the domain. There are extensions like that.

**Comment by mutexd-service** [comment]
I understand, thank you.
