### ISSUE TITLE
429 errors

### ISSUE THREAD

**Issue by FreeBornAngel** [yewtudotbe/invidious-custom#86]
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/7251da46-e453-4b86-a3fc-bc59f968bcff)

I'm getting 429 errors all day today.

**Comment by unixfox** [comment]
Could you give me a screenshot when you open the devtools, click on network tab then on the first request. I need to see the headers sent.

**Comment by FreeBornAngel** [comment]
Is this it?
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/aec9d568-0b8d-4a72-bf81-12a05171aa84)
I didn't see network.
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/8d803ad7-d348-4f71-99fd-f655586cb817)
I wasn't sure about open 'dev tools', so I used cntr shft J and right click inspect.

**Comment by unixfox** [comment]
In the network tab, click on the first request. Accessible from the button  after "Source": 
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/f6b94596-ac7c-4f76-bdea-2a45931a7eea)

Example:
![image](https://github.com/yewtudotbe/invidious-custom/assets/4016501/c2e35906-9da2-4e31-8487-5e8633bcbe6e)

**Comment by FreeBornAngel** [comment]
Better?

![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/302adcd8-b7e8-443e-8af7-fefffd9289ee)

**Comment by unixfox** [comment]
If I could also get the "requests" headers in full that would be awesome.

**Comment by FreeBornAngel** [comment]
It took me a minute.

Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:
gzip, deflate, br
Accept-Language:
en-US,en;q=0.9
Cache-Control:
max-age=0
Connection:
keep-alive
Cookie:
PREFS=%7B%22annotations%22%3Afalse%2C%22annotations_subscribed%22%3Afalse%2C%22autoplay%22%3Atrue%2C%22automatic_instance_redirect%22%3Afalse%2C%22captions%22%3A%5B%22%22%2C%22%22%2C%22%22%5D%2C%22comments%22%3A%5B%22youtube%22%2C%22%22%5D%2C%22continue%22%3Afalse%2C%22continue_autoplay%22%3Afalse%2C%22dark_mode%22%3Atrue%2C%22latest_only%22%3Afalse%2C%22listen%22%3Afalse%2C%22local%22%3Atrue%2C%22watch_history%22%3Afalse%2C%22vr_mode%22%3Atrue%2C%22show_nick%22%3Afalse%2C%22locale%22%3A%22en-US%22%2C%22region%22%3A%22US%22%2C%22max_results%22%3A40%2C%22notifications_only%22%3Afalse%2C%22player_style%22%3A%22invidious%22%2C%22quality_dash%22%3A%22auto%22%2C%22default_home%22%3A%22Popular%22%2C%22feed_menu%22%3A%5B%22Popular%22%2C%22Trending%22%5D%2C%22related_videos%22%3Atrue%2C%22sort%22%3A%22published%22%2C%22speed%22%3A1%2C%22thin_mode%22%3Afalse%2C%22unseen_only%22%3Afalse%2C%22video_loop%22%3Afalse%2C%22extend_desc%22%3Afalse%2C%22volume%22%3A100%2C%22save_player_pos%22%3Afalse%7D; PREFS=%7B%22annotations%22%3Afalse%2C%22annotations_subscribed%22%3Afalse%2C%22autoplay%22%3Atrue%2C%22automatic_instance_redirect%22%3Afalse%2C%22captions%22%3A%5B%22%22%2C%22%22%2C%22%22%5D%2C%22comments%22%3A%5B%22youtube%22%2C%22%22%5D%2C%22continue%22%3Afalse%2C%22continue_autoplay%22%3Afalse%2C%22dark_mode%22%3Atrue%2C%22latest_only%22%3Afalse%2C%22listen%22%3Afalse%2C%22local%22%3Atrue%2C%22watch_history%22%3Afalse%2C%22vr_mode%22%3Atrue%2C%22show_nick%22%3Afalse%2C%22locale%22%3A%22en-US%22%2C%22region%22%3A%22US%22%2C%22max_results%22%3A40%2C%22notifications_only%22%3Afalse%2C%22player_style%22%3A%22invidious%22%2C%22quality_dash%22%3A%22auto%22%2C%22default_home%22%3A%22Popular%22%2C%22feed_menu%22%3A%5B%22Popular%22%2C%22Trending%22%5D%2C%22related_videos%22%3Atrue%2C%22sort%22%3A%22published%22%2C%22speed%22%3A1%2C%22thin_mode%22%3Afalse%2C%22unseen_only%22%3Afalse%2C%22video_loop%22%3Afalse%2C%22extend_desc%22%3Afalse%2C%22volume%22%3A100%2C%22save_player_pos%22%3Afalse%7D; PREFS=%7B%22annotations%22%3Afalse%2C%22annotations_subscribed%22%3Afalse%2C%22autoplay%22%3Atrue%2C%22automatic_instance_redirect%22%3Afalse%2C%22captions%22%3A%5B%22%22%2C%22%22%2C%22%22%5D%2C%22comments%22%3A%5B%22youtube%22%2C%22%22%5D%2C%22continue%22%3Afalse%2C%22continue_autoplay%22%3Afalse%2C%22dark_mode%22%3A%22dark%22%2C%22latest_only%22%3Afalse%2C%22listen%22%3Afalse%2C%22local%22%3Atrue%2C%22watch_history%22%3Afalse%2C%22vr_mode%22%3Atrue%2C%22show_nick%22%3Afalse%2C%22locale%22%3A%22en-US%22%2C%22region%22%3A%22PH%22%2C%22max_results%22%3A40%2C%22notifications_only%22%3Afalse%2C%22player_style%22%3A%22invidious%22%2C%22quality%22%3A%22hd720%22%2C%22quality_dash%22%3A%22auto%22%2C%22default_home%22%3A%22Popular%22%2C%22feed_menu%22%3A%5B%22Popular%22%2C%22Trending%22%5D%2C%22related_videos%22%3Atrue%2C%22sort%22%3A%22published%22%2C%22speed%22%3A1.0%2C%22thin_mode%22%3Afalse%2C%22unseen_only%22%3Afalse%2C%22video_loop%22%3Afalse%2C%22extend_desc%22%3Afalse%2C%22volume%22%3A100%2C%22save_player_pos%22%3Afalse%7D
Dnt:
1
Host:
yewtu.be
Sec-Fetch-Dest:
document
Sec-Fetch-Mode:
navigate
Sec-Fetch-Site:
none
Sec-Fetch-User:
?1
Sec-Gpc:
1
Upgrade-Insecure-Requests:
1
User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by unixfox** [comment]
Thanks. I'll take a look tomorrow.
Until then try to change your IP, maybe by using a VPN or reboot your internet router?

Sorry for the trouble.

**Comment by FreeBornAngel** [comment]
Ok, I can reboot the router easy enough.
Is this not happening to others?
I used the tor option on brave and it got a 429, as well.

Take your time, no hurries.

**Comment by iansmirna** [comment]
I also had the same error all day long. I tried flushing cache, deleting history/cookies + restart, Incognito mode, VPN, nothing worked. 
The error occurs after the main page which loads ok, as soon as i launch a research.

Here is my output: 

Request URL:
https://yewtu.be/search?q=arte+coup+sur+coup
Request Method:
GET
Status Code:
429 Too Many Requests
Remote Address:
[2605:6400:30:ee66::]:443
Referrer Policy:
same-origin
Connection:
keep-alive
Content-Length:
564
Content-Type:
text/html
Date:
Sun, 15 Oct 2023 01:08:35 GMT
Strict-Transport-Security:
max-age=15724800; includeSubDomains; preload
X-Robots-Tag:
'noindex, nofollow, nosnippet, noarchive'
Accept:
text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:
gzip, deflate, br
Accept-Language:
fr-FR,fr;q=0.7
Cache-Control:
max-age=0
Connection:
keep-alive
Host:
yewtu.be
Referer:
https://yewtu.be/
Sec-Ch-Ua:
"Chromium";v="118", "Brave";v="118", "Not=A?Brand";v="99"
Sec-Ch-Ua-Mobile:
?0
Sec-Ch-Ua-Platform:
"macOS"
Sec-Fetch-Dest:
document
Sec-Fetch-Mode:
navigate
Sec-Fetch-Site:
same-origin
Sec-Fetch-User:
?1
Sec-Gpc:
1
Upgrade-Insecure-Requests:
1
User-Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

**Comment by unixfox** [comment]
Could you check if it's fixed or not? If not, then I'll have to dig a bit deeper tomorrow or tonight.

**Comment by FreeBornAngel** [comment]
Still getting the 429.

**Comment by unixfox** [comment]
Big sorry guys! The IP address of my proxy frontend got changed and so it broke the rate limiter, it was like everyone was from a single IP address so that's why you got a "429 Too Many Requests" error.

It's fixed

**Comment by FreeBornAngel** [comment]
Yes!
It is working for me.
Thank you.
