### ISSUE TITLE
502 error

### ISSUE THREAD

**Issue by FreeBornAngel** [yewtudotbe/invidious-custom#90]
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/203d74a2-7fe4-49a5-a6df-8820050653fa)

**Comment by FreeBornAngel** [comment]
Thank you!

**Comment by unixfox** [comment]
Not the first time, I had my disk filled up all the way :smiling_face_with_tear: 

Anyway for errors like this I'm immediately notified.
