### ISSUE TITLE
Missing audio track selection patch

### ISSUE THREAD

**Issue by Skyluker4** [yewtudotbe/invidious-custom#92]
I'd like to add the audio track selection that https://yewtu.be/ has currently to my own instance, but the patch for it is not in this repository. Is it somewhere else, or can you add it?

**Comment by unixfox** [comment]
There is no patch in the invidious code. It's custom backend.

Available here: https://github.com/unixfox/invidious-stripped-down. I offer no support on it, use at your own risk.
