### ISSUE TITLE
Videos won't play

### ISSUE THREAD

**Issue by FreeBornAngel** [yewtudotbe/invidious-custom#95]
**Describe the bug**

The page loads the thumbnail and then nothing.

**Steps to Reproduce**

Open video

**Screenshots**

![image](https://github.com/iv-org/invidious/assets/18445737/bf60dffa-369c-4360-9c70-64e01e59371b)

**Additional context**

It's been a couple days of this.

 - Browser (if applicable): brave
 - OS (if applicable): linux mint
-->

**Comment by unixfox** [comment]
Only DASH does not work. If you switch to HD720 it works.

Something broke and I haven't had the time to fix it for the moment.

**Comment by FreeBornAngel** [comment]
![image](https://github.com/yewtudotbe/invidious-custom/assets/18445737/63fc3266-a447-4864-826e-f36c3c80b7b5)

I must have done that last time.
No hurries.

**Comment by unixfox** [comment]
fixed. thx for the report

**Comment by unixfox** [comment]
still not fixed, reopening

**Comment by FreeBornAngel** [comment]
Seems to be working now.
Thank you!

**Comment by unixfox** [comment]
Odd that was not working when I did test but now it works again. Great.
