### ISSUE TITLE
Video shows: "The following content is not available on this app. Watch this content on the latest version of Youtube"

### ISSUE THREAD

**Issue by syildizz** [yewtudotbe/invidious-custom#98]
Video gives the following error when viewing any video on yewtu.be.

The issue does not exist with other indivious instances.

The issue started occurring at 28.03.2024.

![Screenshot 2024-03-30 at 00-45-38 Helal Olsun Beklemiyordum 😯 Kanal Hikayeleri 4  Bölüm TepkiKolik](https://github.com/yewtudotbe/invidious-custom/assets/118059676/58289afa-94ea-49c1-9452-a30fa90b7fd3)

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4498
